FROM golang:1.22-alpine AS build
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags='-s -w' -o /out/prom-udp-sender ./cmd/sender
FROM scratch
COPY --from=build /out/prom-udp-sender /prom-udp-sender
USER 65532:65532
ENTRYPOINT ["/prom-udp-sender"]
