{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pur.fullname" . }}
  labels:
    {{- include "pur.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.key }}: {{ required "secret.value or secret.existingSecret is required" .Values.secret.value | quote }}
{{- end }}
