apiVersion: v1
kind: Service
metadata:
  name: {{ include "pur.fullname" . }}-metrics
  labels:
    {{- include "pur.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "pur.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      protocol: TCP
      port: {{ .Values.metricsService.port }}
      targetPort: {{ .Values.receiver.httpPort }}
